baseURL = 'https://CGRG-lab.github.io/doc-archive/'
languageCode = 'en-us'
title = 'doc-archive'
theme = "docsy"


# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true
[languages]
[languages.en]
description = "Docsy does docs"
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.zh]
description = "Docsy does docs"
languageName ="中文"
contentDir = "content/zh"


# Top-level menu
[[menu.main]]
  name = "CGRG website"
  weight = 50
  url = "https://cgrg.synology.me/CGRG/"
  pre = "<i class='fas fa-external-link-alt'></i>" 
[[menu.main]]
  name = "GitHub"
  weight = 60
  url = "https://github.com/CGRG-lab/doc-archive/"
  pre = "<i class='fab fa-github'></i>" 

# Will give values to .Lastmod etc.
enableGitInfo = true

[params]
copyright = "CGRG"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
sidebar_menu_foldable = true
sidebar_cache_limit = 10
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false

[params.katex]
enable = true
html_dom_element = "document.body"

# enable display of chemical equations and physical units via mhchem extension
[params.katex.mhchem]
enable = true

[params.print]
disable_toc = false

[params.markmap]
enable = true

# [params.taxonomy]
# taxonomyCloud = ["tags", "categories"] # set taxonomyCloud = [] to hide taxonomy clouds
# taxonomyCloudTitle = ["Tag Cloud", "Cloud of Categories"] # if used, must have same lang as taxonomyCloud
# taxonomyPageHeader = ["tags", "categories"] # set taxonomyPageHeader = [] to hide taxonomies on the page headers

[taxonomies]
tag = "tags"
category = "categories"